### ISSUE TITLE
数据集“Movie_all_item_list.dat”的处理方法

### ISSUE THREAD

**Issue by LitwhtLxy** [wangshanyw/DCCDR#2]
作者您好，阅读您的论文及代码学习后，有关数据集存在疑虑。请问“Movie_all_item_list.dat”、“Music_all_item_list.dat”、“cell_all_item_list.dat”、“Elec_all_item_list.dat”等类似的输入数据，是如何处理得到的呢，您提供的源码中好像没有有关这方面的处理（Amazon数据集中无此类型数据），请您有空时帮解答，如果可以麻烦您提供有关部分至邮箱[1507470160@qq.com](mailto:1507470160@qq.com)，谢谢您。

**Comment by CreaterLL** [comment]
> 作者您好，阅读您的论文及代码学习后，有关数据集存在疑虑。请问“Movie_all_item_list.dat”、“Music_all_item_list.dat”、“cell_all_item_list.dat”、“Elec_all_item_list.dat”等类似的输入数据，是如何处理得到的呢，您提供的源码中好像没有有关这方面的处理（Amazon数据集中无此类型数据），请您有空时帮解答，如果可以麻烦您提供有关部分至邮箱[1507470160@qq.com](mailto:1507470160@qq.com)，谢谢您。



> 作者您好，阅读您的论文及代码学习后，有关数据集存在疑虑。请问“Movie_all_item_list.dat”、“Music_all_item_list.dat”、“cell_all_item_list.dat”、“Elec_all_item_list.dat”等类似的输入数据，是如何处理得到的呢，您提供的源码中好像没有有关这方面的处理（Amazon数据集中无此类型数据），请您有空时帮解答，如果可以麻烦您提供有关部分至邮箱[1507470160@qq.com](mailto:1507470160@qq.com)，谢谢您。

您好，我也有同样的困惑，请问解决了吗？
